name: Create Beta Release PR

env:
  APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
  APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}

on:
  workflow_dispatch:
    inputs:
      qa_branch:
        description: "QA branch (qa/*)"
        required: true
        type: string

jobs:
  promote-to-beta:
    name: Promote To Beta
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Setup Github App
        id: github-app
        if: ${{ env.APP_CLIENT_ID && env.APP_PRIVATE_KEY }}
        uses: abhisin98/avivox-action-setup-github-app@v1
        with:
          app-client-id: ${{ env.APP_CLIENT_ID }}
          app-private-key: ${{ env.APP_PRIVATE_KEY }}

      - name: Check out code
        uses: actions/checkout@v7
        with:
          token: ${{ steps.github-app.outputs.app-token || github.token }}
          fetch-depth: 0 # Fetch full history

      - name: Promote Branch
        uses: abhisin98/avivox-action-promotion-engine@v1
        with:
          source-branch-name: ${{ github.event.inputs.qa_branch }}
          promotion-target: beta
          github-token: ${{ steps.github-app.outputs.app-token || github.token }}
