name: Production Deployment

env:
  # Environment Variables:
  # - Used to configure settings such as database connections and API keys.
  # - It's best to store sensitive values in GitHub Secrets for security.
  RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }} # get this in account settings "https://railway.com/account/tokens" (make sure this is NOT a project token), and scope it to your account (not a workspace)
  RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }} # project ID
  RAILWAY_ENVIRONMENT_ID: ${{ secrets.RAILWAY_ENVIRONMENT_ID }} # railway environment to duplicate from
  RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }} # service ID to inject database variable into
  # RAILWAY_WORKSPACE_ID: ${{ secrets.RAILWAY_WORKSPACE_ID }} # if you are linking to a project in a workspace, uncomment this
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code # Fetches the latest code from the repository.
        uses: actions/checkout@v6

      - name: Setup # Executes setup scripts for dependencies.
        uses: ./.github/actions/setup

      - name: Run CI Action
        uses: ./.github/actions/ci

  deploy-web:
    name: Deploy Web (Prod)
    needs: ci
    runs-on: ubuntu-latest
    environment:
      name: Web
      url: ${{ steps.deploy.outputs.url }} # Stores the deployment URL dynamically
    steps:
      - name: Check out code # Fetches the latest code from the repository.
        uses: actions/checkout@v6

      - name: Deploy (Production)
        id: deploy
        uses: ./.github/actions/railway-deploy
        with:
          api-token: ${{ env.RAILWAY_API_TOKEN }}
          project-id: ${{ env.RAILWAY_PROJECT_ID }}
          environment-id: ${{ env.RAILWAY_ENVIRONMENT_ID }}
          service-id: ${{ env.RAILWAY_SERVICE_ID }}

      - name: Deployment Info
        run: |
          echo "Deployed at: ${{ steps.deploy.outputs.url }}"

  publish-packages:
    name: Publish Packages (Prod)
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: write # required for tags + releases
      # pull-requests: write  # required for PR comments
    steps:
      - name: Check out code # Fetches the latest code from the repository.
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Fetch full history for git-cliff

      - name: Setup # Executes setup scripts for dependencies.
        uses: ./.github/actions/setup

      - name: Configure npm
        run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

      - name: Publish Packages (Production)
        uses: ./.github/actions/changelogs
        with:
          release-type: auto
          # pr-number: ${{ github.event.pull_request.number }} # PR number
          # head-sha: ${{ github.event.pull_request.head.sha }} # commit

          do-git: "true"
          # commit-message: ""
          create-release: "true"
          github-token: ${{ env.GITHUB_TOKEN }}

          do-publish: "true"
          publish-tool: "pnpm"
          publish-access: "public"
          publish-tag: "latest"
          # publish-registry: ""
